Updated Platforms Guide
bsmg/wiki pull request #325
Opened 2021-04-18 10:47 UTC by affederaffe

Everything is now located in the CustomPlatforms repository for simplicity (like CustomAvatars does), therefore the updated guide. You probably don't want to merge this until I create the release.

2021-04-18 18:53 UTC, namaki-mono requested changes
Hello! I noticed a few minor issues (e.g. spelling, formatting, etc.) that should be easy to fix.

2021-04-18 18:53 UTC, namaki-mono commented on wiki/models/platforms-guide.md
> +The `Spectrogram` script works like the track rings script and also requires a prefab.
Spectogram on line 63 vs. Spectrogram on line 66, unsure of which one is the correct spelling, but the one on line 66 has an 'r'.

2021-04-18 18:53 UTC, namaki-mono commented on wiki/models/platforms-guide.md
> +The `Event Manager` is the most useful script. With it you can trigger an action on any beat saber event (even unused).
Nitpick: "beat saber" should be capitalized as "Beat Saber" for consistency with the rest of the page.

2021-04-18 18:53 UTC, namaki-mono commented on wiki/models/platforms-guide.md
> +![Rotation Effetcs](~@images/models/platforms/RotationEffects.png)
"Rotation Effetcs" on line 69 and 70, should be "Rotation Effects".

2021-04-18 18:53 UTC, namaki-mono commented on wiki/models/platforms-guide.md
> +Both the `RotationEventEffect` and the `PairRotationEventEffec`t rotate your GameObjects based on the assigned song event.
The final character of `PairRotationEventEffect` is outside of the formatting block.

2021-04-18 18:53 UTC, namaki-mono commented on wiki/models/platforms-guide.md
> +This will get stretched and shrunk according to the sound of the game and the variables provided
Nitpick: Period missing at the end of this sentence.

2021-04-18 18:53 UTC, namaki-mono commented on wiki/models/platforms-guide.md
> +For adding an event press the + button underneath On Trigger ().
Maybe: The `+` button and `On Trigger ()` terms lost their block formatting, unsure if this was intentional.

2021-04-18 18:53 UTC, namaki-mono commented on wiki/models/platforms-guide.md
> +these actions are reflected in-game and the corrosponding platform is deleted, loaded or updated.
corrosponding -> corresponding

2021-04-24 07:44 UTC, bloodcloak approved these changes

2021-04-24 07:52 UTC, merged