Document Lighting v3
bsmg/wiki pull request #497
Opened 2023-05-06 09:27 UTC by mcendu

- add introduction of v3 for basic lighting
- revise text for Lighting Events

2023-05-07 05:35 UTC, bloodcloak commented
![image](https://user-images.githubusercontent.com/59000966/236659657-ae291f2c-1627-4939-a6af-cda4ce06a14d.png)
this is the current breakdown of the pages. So I guess with that in mind maybe overview of the system in basic with all of the more vanilla technical settings in intermediate? Then rest in advanced.

2023-05-07 05:52 UTC, bloodcloak requested changes
The double spaces after the end of a line is what tells the site renderer to create a new line. Instead of joining the two adjacent together. 

Should not remove this double space in
Basic Lighting Lines: 55, and 241
Intermediate Lighting Lines 108, 127, 160, and 167

2023-05-07 05:52 UTC, bloodcloak commented on wiki/mapping/intermediate-lighting.md
> +need to start at the 1st chunk; the offset, titled <q>Light #</q>, is
Linting error blocks. replace the <q> and </q> with ` to highlight/differentiate or just regular "

2023-05-07 05:52 UTC, bloodcloak commented on wiki/mapping/intermediate-lighting.md
> +is not desired, <q>Affect First</q> can be checked to make
See suggestion to replace above

2023-05-07 05:52 UTC, bloodcloak commented on wiki/mapping/basic-lighting.md
> +In Weave and later environments, or v3 environments, the set of objects
`In Weave and later environments, or v3 environments,` suggest `In environments that use the v3 Group Lighting System (Weave and later),`

2023-05-07 08:16 UTC, mcendu commented
I have no access to my computer for the time being, so it might take some time before I can actually apply the suggestions.

On the lint error: I have to admit that the q element is not appropriately used here; per WHATWG HTML standard, this element cannot be used when it does not represent a quote. Would replace with &ldquo; and &rdquo; pairs once I am back.

> Should not remove this double space in
Basic Lighting Lines: 55, and 241
Intermediate Lighting Lines 108, 127, 160, and 167

My editor is set to automatically trim trailing whitespaces. While I personally prefer to use <br> for this purpose, using EditorConfig to tell the editor to not trim trailing whitespaces might better fit our markup formatting style.

> In Weave and later environments, or v3 environments, suggest In environments that use the v3 Group Lighting System (Weave and later),

Agreed.

Message ID: ***@***.***>

2023-05-07 08:24 UTC, mcendu commented
P.S. The EditorConfig actually already tells the editor to not trim whitespaces. Something is wrong with my configuration…
________________________________
发件人: Nathan Du ***@***.***>
发送时间: Sunday, May 7, 2023 4:16:03 PM
收件人: bsmg/wiki ***@***.***>
主题: Re: [bsmg/wiki] Document Lighting v3 (PR #497)

I have no access to my computer for the time being, so it might take some time before I can actually apply the suggestions.

On the lint error: I have to admit that the q element is not appropriately used here; per WHATWG HTML standard, this element cannot be used when it does not represent a quote. Would replace with &ldquo; and &rdquo; pairs once I am back.

> Should not remove this double space in
Basic Lighting Lines: 55, and 241
Intermediate Lighting Lines 108, 127, 160, and 167

My editor is set to automatically trim trailing whitespaces. While I personally prefer to use <br> for this purpose, using EditorConfig to tell the editor to not trim trailing whitespaces might better fit our markup formatting style.

> In Weave and later environments, or v3 environments, suggest In environments that use the v3 Group Lighting System (Weave and later),

Agreed.

Message ID: ***@***.***>

2023-05-13 01:03 UTC, XAce1337manX commented
🙏 The table reformat. I can add preview images for the environments later.

Wonder if we should move the table to another page considering it takes up over half the page now.

2023-05-25 02:04 UTC, bloodcloak approved these changes

2023-05-25 02:09 UTC, merged