Questmodding Wiki Update
bsmg/wiki pull request #526
Opened 2023-08-12 20:06 UTC by hdgamer1404Jonas

I've took some time to more or less rework the Quest Modding Guides from ground up. Most of the information in the quest-modding.md seemed outdated and difficult to understand for new users. I hope this version can be considered as an replacement for the current guide.

2023-08-13 23:11 UTC, joebobbio commented on wiki/quest-modding-bmbf.md
> +It's recommended to tape up the proximity sensor between the lenses of your Quest. This prevents it from
FYI there is a button in sidequest to turn off the proximity sensor which should probably be suggested instead

2023-08-31 01:23 UTC, bloodcloak requested changes

2023-08-31 01:23 UTC, bloodcloak commented on wiki/quest-modding-qavs.md
> +# Quest Modding using QAVS
Add relevant images as called out in the bmbf version

2023-09-03 01:20 UTC, bloodcloak requested changes

2023-09-03 01:20 UTC, bloodcloak commented on wiki/.assets/images/beginners-guide/squninstall.png
It is hard to see the arrow and number 1. Would suggest having it on a white background

2023-09-13 00:40 UTC, bloodcloak approved these changes

2023-09-13 00:41 UTC, merged