Minor updates to "Testing on a Quest"
bsmg/wiki pull request #581
Opened 2024-03-23 02:03 UTC by TheCzar1994

SideQuest apparently has an "Experimental Web Installer" now. This clarifies to use the "Advanced Installer" compatible with these instructions. Also removes "1. Locate your WIP song folder on your PC." as this is being explained following it so it seems redundant and then re-numbers the rest.

2024-04-04 02:35 UTC, bloodcloak requested changes

2024-04-04 02:35 UTC, bloodcloak commented on wiki/mapping/index.md
> +walk you through how to use it below.
```When [downloading SideQuest](https://sidequestvr.com/setup-howto), be sure to download the `Advanced Installer`.```

2024-04-04 02:35 UTC, bloodcloak commented on wiki/mapping/index.md
> +:::tip NOTE
`:::warning NOTE`

2024-04-04 02:36 UTC, bloodcloak commented
Requesting since I'm not able to push the format suggestion to the branch

2024-04-04 12:38 UTC, TheCzar1994 commented
Sorry about that! Should be able to in the future if needed but I made the suggested changes.

2024-04-05 01:29 UTC, bloodcloak approved these changes

2024-04-05 01:30 UTC, merged